//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIFIET.GestionProgramas.Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASIGNATURA
    {
        public string IDASIGNATURA { get; set; }
        public string IDPLANESTUDIOS { get; set; }
        public string NOMADIGNATURA { get; set; }
        public string CORREQUISITOSASIGNATURA { get; set; }
        public string PREREQUISITOSASIGNATURA { get; set; }
        public Nullable<short> SEMESTREASIGNATURA { get; set; }
        public Nullable<decimal> INTENSIDADHORARIA { get; set; }
        public string MODALIDAD { get; set; }
        public string CLASIFICACION { get; set; }
        public string ESTADOASIGNATURA { get; set; }
    
        public virtual PLANESTUDIO PLANESTUDIO { get; set; }
    }
}
