//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIFIET.GestionProgramas.Datos.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GestionProgramasEntities : DbContext
    {
        public GestionProgramasEntities()
            : base("name=GestionProgramasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ASIGNATURA> ASIGNATURAs { get; set; }
        public DbSet<PROGRAMA> PROGRAMAs { get; set; }
        public DbSet<PLANESTUDIO> PLANESTUDIOS { get; set; }
    }
}
