//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIFIET.GestionProgramas.Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLANESTUDIO
    {
        public PLANESTUDIO()
        {
            this.ASIGNATURAS = new HashSet<ASIGNATURA>();
        }
    
        public string IDPLANESTUDIOS { get; set; }
        public string IDPROGRAMA { get; set; }
        public string NOMPLANESTUDIOS { get; set; }
        public string DESPLANESTUDIOS { get; set; }
        public string FECINICIOPLANESTUDIOS { get; set; }
        public string FECFINPLANCONTENIDO { get; set; }
        public string ESTADOPLANESTUDIOS { get; set; }
    
        public virtual ICollection<ASIGNATURA> ASIGNATURAS { get; set; }
        public virtual PROGRAMA PROGRAMA { get; set; }
    }
}
