//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIFIET.GestionUsuarios.Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERMISO
    {
        public PERMISO()
        {
            this.ROL_TIENE_PERMISOS = new HashSet<ROL_TIENE_PERMISOS>();
        }
    
        public string IDPERMISO { get; set; }
    
        public virtual ICollection<ROL_TIENE_PERMISOS> ROL_TIENE_PERMISOS { get; set; }
    }
}
