//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIFIET.GestionUsuarios.Datos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROL
    {
        public ROL()
        {
            this.USUARIOs = new HashSet<USUARIO>();
        }
    
        public string IDROL { get; set; }
        public string NOMROL { get; set; }
        public string DESCROL { get; set; }
    
        public virtual ROL_TIENE_PERMISOS ROL_TIENE_PERMISOS { get; set; }
        public virtual ICollection<USUARIO> USUARIOs { get; set; }
    }
}
